server:
  port: 8081

spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:orderdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


  kafka:
    bootstrap-servers: kafka.ns-dapr-test1.svc.cluster.local:9092
    properties:
      security:
        protocol: "SASL_PLAINTEXT"
      sasl:
        mechanism: "SCRAM-SHA-256"
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="zkgtseD1q3";

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

logging:
  level:
    root: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"